# Copyright (c) Mixed Reality Toolkit Contributors
# Licensed under the BSD 3-Clause

# Build for PR validation

variables:
  - template: Config/settings.yaml

resources:
  repositories:
    - repository: PipelineTools
      type: git
      endpoint: ToolsAccess
      name: tools.internal
      ref: 9f54deb8134c5c910a302c5d70f61a3dc5ffc6fa

trigger: none # disable CI

stages:
  - stage: UnityValidation
    jobs:
      - job: BuildStandaloneAndTest
        pool: Unity_2021.3.21f1_Pool
        steps:
          - checkout: self
            fetchDepth: 3

          - checkout: PipelineTools

          - template: Templates/unity.yaml
            parameters:
              Platform: Standalone
              RunTests: true

      - job: BuildUWP
        pool: Unity_2021.3.21f1_Pool
        steps:
          - checkout: self
            fetchDepth: 3

          - checkout: PipelineTools

          - template: Templates/unity.yaml
            parameters:
              Platform: UWP

      - job: BuildAndroid
        pool: Unity_2021.3.21f1_Pool
        steps:
          - checkout: self
            fetchDepth: 3

          - checkout: PipelineTools

          - template: Templates/unity.yaml
            parameters:
              Platform: Android
