Copy-Item '..\MRTK Gaze Controller.prefab' '.\MRTK XRI Gaze.prefab'
Copy-Item '..\MRTK Interaction Manager.prefab' '.\MRTK XRI Interaction Manager.prefab'
Copy-Item '..\MRTK LeftHand Controller.prefab' '.\MRTK XRI LeftHand.prefab'
Copy-Item '..\MRTK RightHand Controller.prefab' '.\MRTK XRI RightHand.prefab'
Copy-Item '..\MRTK XR Rig.prefab' '.\MRTK XRI Rig.prefab'
git checkout -- '..\MRTK Gaze Controller.prefab'
git checkout -- '..\MRTK Interaction Manager.prefab'
git checkout -- '..\MRTK LeftHand Controller.prefab'
git checkout -- '..\MRTK RightHand Controller.prefab'
git checkout -- '..\MRTK XR Rig.prefab'
